CREATE TABLE [dbo].[MATCH]
(
	[MATCH_ID] BIGINT NOT NULL PRIMARY KEY, 
    [WINNER_ID] BIGINT NULL, 
    [LOSER_ID] BIGINT NULL, 
    [PLAYER1_ID] BIGINT NULL, 
    [PLAYER2_ID] BIGINT NULL, 
    [TOURNAMENT_ID] BIGINT NOT NULL, 

    CONSTRAINT [FK_MATCH_TOURNAMENT_1] FOREIGN KEY ([TOURNAMENT_ID]) REFERENCES [TOURNAMENT]([TOURNAMENT_ID]), 
    CONSTRAINT [FK_MATCH_PARTICIPANT_1] FOREIGN KEY ([WINNER_ID]) REFERENCES [PARTICIPANT]([PARTICIPANT_ID]),
	CONSTRAINT [FK_MATCH_PARTICIPANT_2] FOREIGN KEY ([LOSER_ID]) REFERENCES [PARTICIPANT]([PARTICIPANT_ID]),
	CONSTRAINT [FK_MATCH_PARTICIPANT_3] FOREIGN KEY ([PLAYER1_ID]) REFERENCES [PARTICIPANT]([PARTICIPANT_ID]),
	CONSTRAINT [FK_MATCH_PARTICIPANT_4] FOREIGN KEY ([PLAYER2_ID]) REFERENCES [PARTICIPANT]([PARTICIPANT_ID])
)
