CREATE TABLE [dbo].[PARTICIPANT]
(
	[PARTICIPANT_ID] BIGINT NOT NULL PRIMARY KEY DEFAULT NEXT VALUE FOR SEQ_PARTICIPANT_ID, 
    [CHALLONGE_USERNAME] NVARCHAR(50) NULL, 
    [NAME] NVARCHAR(50) NULL
)
