CREATE TABLE [dbo].[SET]
(
	[MATCH_ID] BIGINT NOT NULL, 
    [SET_NO] INT NOT NULL, 
    [PLAYER1_SCORE] INT NULL, 
    [PLAYER2_SCORE] INT NULL, 

    CONSTRAINT [PK_SET] PRIMARY KEY ([MATCH_ID], [SET_NO])
)
