CREATE VIEW [dbo].[VW_WEIGHTED_WIN_LOSS]
	AS
SELECT
	P.CHALLONGE_USERNAME,
	CAST(ISNULL(WINS.WIN,0) AS DECIMAL(10,2)) ADJUSTED_WINS,
	CAST(ISNULL(LOSES.LOSS,0) AS DECIMAL(10,2)) ADJUSTED_LOSSES,
	ISNULL(WINS.WIN,0)*100/(ISNULL(WINS.WIN,0)+ISNULL(LOSES.LOSS,0)) ADJUSTED_WIN_RATE 
FROM DB_PLAYER P

LEFT JOIN (
	SELECT 
		P.PLAYER_ID,
		SUM(WEIGHTED_WINS.WIN_RATE)/50 WIN
	FROM DB_PLAYER P

	JOIN DB_MATCH M
	ON M.WINNER_ID = P.PLAYER_ID
	AND M.MATCH_ID IN (
		SELECT 
			MATCH_ID 
		FROM DB_SET
		WHERE PLAYER1_SCORE + PLAYER2_SCORE >0 )

	JOIN DB_PLAYER PL
	ON PL.PLAYER_ID = M.LOSER_ID

	JOIN (
		SELECT
			P.PLAYER_ID, 
			CAST(ISNULL(W.WINS,0)*100/(ISNULL(W.WINS,0)+ISNULL(L.LOSS,0)) AS DECIMAL(10,2)) WIN_RATE
		FROM DB_PLAYER P

		LEFT JOIN (
			SELECT
				P.PLAYER_ID,
				COUNT(*) WINS
			FROM DB_PLAYER P

			JOIN DB_MATCH M
			ON M.WINNER_ID = P.PLAYER_ID
			AND M.MATCH_ID IN (
				SELECT MATCH_ID 
				FROM DB_SET 
				WHERE PLAYER1_SCORE + PLAYER2_SCORE > 0)
			GROUP BY P.PLAYER_ID) W 
		ON W.PLAYER_ID=P.PLAYER_ID

		LEFT JOIN (
			SELECT
				P.PLAYER_ID,
				COUNT(*) LOSS
			FROM DB_PLAYER P

			JOIN DB_MATCH M
			ON M.LOSER_ID = P.PLAYER_ID
			AND M.MATCH_ID IN (
				SELECT MATCH_ID 
				FROM DB_SET 
				WHERE PLAYER1_SCORE + PLAYER2_SCORE > 0)
			GROUP BY P.PLAYER_ID) L
		ON L.PLAYER_ID = P.PLAYER_ID) WEIGHTED_WINS 
	ON WEIGHTED_WINS.PLAYER_ID = PL.PLAYER_ID
	GROUP BY P.PLAYER_ID) WINS 
ON WINS.PLAYER_ID = P.PLAYER_ID

LEFT JOIN (
	SELECT
		P.PLAYER_ID,
		SUM(WEIGHTED_LOSES.LOSS_RATE)/50 LOSS
	FROM DB_PLAYER P

	JOIN DB_MATCH M 
	ON M.LOSER_ID = P.PLAYER_ID
	AND M.MATCH_ID IN (
		SELECT MATCH_ID 
		FROM DB_SET 
		WHERE PLAYER1_SCORE + PLAYER2_SCORE > 0)

	JOIN DB_PLAYER PL 
	ON PL.PLAYER_ID = M.WINNER_ID

	JOIN (
		SELECT
			P.PLAYER_ID, 
			CAST(100-ISNULL(W.WINS,0)*100/(ISNULL(W.WINS,0)+ISNULL(L.LOSS,0)) AS DECIMAL (10,2)) LOSS_RATE
		FROM DB_PLAYER P

		LEFT JOIN (
			SELECT
				P.PLAYER_ID,
				COUNT(*) WINS
			FROM DB_PLAYER P

			JOIN DB_MATCH M
			ON M.WINNER_ID = P.PLAYER_ID
			AND M.MATCH_ID IN (
				SELECT MATCH_ID 
				FROM DB_SET 
				WHERE PLAYER1_SCORE + PLAYER2_SCORE > 0)
			GROUP BY P.PLAYER_ID) W
		ON W.PLAYER_ID=P.PLAYER_ID

		LEFT JOIN ( 
			SELECT
				P.PLAYER_ID,
				COUNT(*) LOSS
			FROM DB_PLAYER P

			JOIN DB_MATCH M 
			ON M.LOSER_ID = P.PLAYER_ID
			AND M.MATCH_ID IN (
				SELECT
					MATCH_ID
				FROM DB_SET 
				WHERE PLAYER1_SCORE + PLAYER2_SCORE > 0)
			GROUP BY P.PLAYER_ID ) L 
		ON L.PLAYER_ID = P.PLAYER_ID ) WEIGHTED_LOSES 
	ON WEIGHTED_LOSES.PLAYER_ID = PL.PLAYER_ID
	GROUP BY P.PLAYER_ID ) LOSES
ON LOSES.PLAYER_ID=P.PLAYER_ID

WHERE P.CHALLONGE_USERNAME <> 'UNKNOWN'
--AND ISNULL(WIN,0) + ISNULL(LOSS,0) > 3
--AND CHALLONGE_USERNAME <> 'BRUSCHKE'
--AND CHALLONGE_USERNAME <> 'JONATHANFLORENTINO'