CREATE TABLE [dbo].[DB_TEAMS_CHANNEL]
(
	[TEAM_ID] NVARCHAR(50) NOT NULL,
	[CHANNEL_ID] NVARCHAR(50) NOT NULL,
	[CHANNEL_NAME] NVARCHAR(50) NULL,

	CONSTRAINT [PK_DB_TEAMS_CHANNEL] PRIMARY KEY ([CHANNEL_ID], [TEAM_ID])
)
