CREATE TABLE [dbo].[MATCH]
(
	[MATCH_ID] [NUMERIC](18, 0) PRIMARY KEY,
	[WINNER_ID] [NUMERIC](18, 0) NULL,
	[LOSER_ID] [NUMERIC](18, 0) NULL,
	[PLAYER1_ID] [NUMERIC](18, 0) NULL,
	[PLAYER2_ID] [NUMERIC](18, 0) NULL,

	[LAST_CHECK_DATE] [DATETIME2](7) NOT NULL
)

GO