CREATE TABLE [dbo].[SET]
(
	[MATCH_ID] [NUMERIC](18, 0) PRIMARY KEY,
	[SET_NO] [NUMERIC](4, 0) PRIMARY KEY,
	[PLAYER1_SCORE] [NUMERIC](4, 0) NULL,
	[PLAYER2_SCORE] [NUMERIC](4, 0) NULL,

	[LAST_CHECK_DATE] [DATETIME2](7) NOT NULL
)

GO